### PR TITLE
Update ATADA-Coin with Decimals(2) test

### PR DESCRIPTION
**Pull request by gitmachtl**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [X] Metadata related change
- [ ] Other

## Checklist:

- [X] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by gitmachtl** [comment]
@piotr-iohk do you have time to merge that PR?

**Comment by mmahut** [comment]
@gitmachtl as far as I know it was decided to not integrate decimals for non-SC native assets.

**Comment by gitmachtl** [comment]
https://github.com/input-output-hk/metadata-registry-testnet/pull/109

**Comment by gitmachtl** [comment]
also, the token-metadata-creator is updated to have decimals as a parameter now

**Comment by mmahut** [comment]
Odd, there is no rational given for that change. I wonder how they plan to resolve the problem with hw wallets.

**Comment by gitmachtl** [comment]
i wondered about that too...

**Pull request merged**
