### PR TITLE
remove old GRAB Policy

### PR DESCRIPTION
**Pull request by solidsnakedev**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [ ] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by solidsnakedev** [comment]
@AndrewWestberg could you by any chance have a look at this PR and merge?

**Comment by AndrewWestberg** [comment]
> @AndrewWestberg could you by any chance have a look at this PR and merge?

I don't think I have access to do the removal. If you split it into two prs, I can approve the new one.

**Comment by AndrewWestberg** [comment]
I went ahead and merged it. Not sure how to clean up the file from the old one though. Somebody from IOG will need to fix that.

**Comment by solidsnakedev** [comment]
Thanks! @AndrewWestberg

**Pull request merged**
