### PR TITLE
Add cBTC test token

### PR DESCRIPTION
**Pull request by solidsnakedev**
# Pull Request Template

## Description

Please include a short summary of the changes in this PR.

## Type of change

- [x] Metadata related change
- [ ] Other

## Checklist:

- [x] For metadata related changes, this PR code passes the Github Actions metadata validation

## Metadata PRs

Please note it may take up to 4 hours for merged changes to take effect on the metadata server.

### CODE REVIEW

**Comment by AndrewWestberg** [comment]
@solidsnakedev Why are there no signatures for this token info?

**Comment by solidsnakedev** [comment]
> @solidsnakedev Why are there no signatures for this token info?

This is a Plutus minting policy, I can use an arbitrary `skey` if that's allowed

**Comment by AndrewWestberg** [comment]
I'm honestly not sure what we're supposed to use in the event the token is minted with plutus. Do you happen to know @disassembler ?  Is it better to leave all signatures blank, or use a random skey?

**Comment by gitmachtl** [comment]
> I'm honestly not sure what we're supposed to use in the event the token is minted with plutus. Do you happen to know @disassembler ? Is it better to leave all signatures blank, or use a random skey?

It was manually greenlit in the past.

**Comment by AndrewWestberg** [comment]
@solidsnakedev Go ahead and remove the signatures again. I'll just get it merged.

**Comment by AndrewWestberg** [comment]
According to docs, signed by any key you control is fine.

**Pull request merged**
